### PR TITLE
Turkish translation

### PR DESCRIPTION
**Pull request by xe1st**
Hope I did everything right :D

### CODE REVIEW

**Comment by maelchiotti** [comment]
Hi @xe1st! Thank you very much for your contribution! This is the first time ever I receive a pull request! Some things need to be added still, but I'll take care of it.

Would you like to be credited in the app and in the Readme with a link to your GitHub account?

**Comment by maelchiotti** [comment]
Hi again @xe1st, there is one string that wasn't in the .arb files that I'm missing. Could you give me its translation here? Thanks. It's this: `Welcome to Material Notes!`.

**Comment by xe1st** [comment]
> Hi again @xe1st, there is one string that wasn't in the .arb files that I'm missing. Could you give me its translation here? Thanks. It's this: `Welcome to Material Notes!`.

```Material Notes'a hoşgeldin! ```

**Comment by maelchiotti** [comment]
Closing this as I moved your translations to a new branch to make code changes to the app, see #23

**Pull request closed without merging**
