### PR TITLE
initial Fastlane structures from IzzyOnDroid

### PR DESCRIPTION
**Pull request by IzzySoft**
Guess you need this for your RFP at F-Droid :wink: For help with building on this and maintaining it, be welcome to the [IzzyOnDroid Fastlane Documentation](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane)

### CODE REVIEW

**Comment by maelchiotti** [comment]
Oh I did add the fastlane structure, but it's only on the dev branch and not on the main one. I will merge that into main asap. Thank you for your help @IzzySoft!

Also, are you the one that translated the descriptions into German? Can I add that into my fastlane structure?

**Comment by maelchiotti** [comment]
@IzzySoft I merged the fastlane structure into the `main` branch.

I did not however keep your german version of the description, as it was out of date. Feel free to open a PR if you ever wish to improve the machine translation!

And thanks again for your help ☺️

**Comment by IzzySoft** [comment]
> I did not however keep your german version of the description, as it was out of date. Feel free to open a PR if you ever wish to improve the machine translation!

Thanks – but that would then outage again. Maybe consider something like Weblate for translations then, so permanent contributors can keep it updated.

As for the fastlane now in main: `video.txt`is empty (you could simply skip it). `full_description.txt` will not render ideal (if you'd have an empty line before the bullet-point lists as well, it would render fine as Markdown – so longer bullet-point-texts would not break the list either). Do you want me to enable it as-is (just converting the fulldesc then by replacing line-breaks with `<br>`, as F-Droid does) – or shall I rather wait for the files to be updated?

**Comment by maelchiotti** [comment]
Yes, I started to look into online translation services, that would clearly be best.

I will remove `video.txt`.

For `full_description.txt`, I used the same format that the one that fastlane pulled from the Play Store when I initialized it. But I can add <p> tags for paragraphs, <ul><li> tags for the lists and replace line breaks with <br>, would that fix everything?

**Comment by IzzySoft** [comment]
You can either make it "complete HTML" as you described (I see no need for `<br>` there, though) – which would format best with F-Droid **and** IzzyOnDroid), or make it Markdown-compatible (inserting an empty line before each list, so the lists are clearly separated; that would work the same way with IoD but look less optimal with F-Droid). So basically:

```html
<p><b>Take notes</b></p><ul>
<li>Write text notes (title and content)</li>
<li>Take advantage of the advanced formatting options, including checklists</li>
<li>Undo and redo your changes while editing</li>
<li>Use the quick action from your home screen to quickly add a note</li>
</ul>
```

and so on would produce the best results there.

**Comment by maelchiotti** [comment]
Ok, I will make it "complete HTML" as you showed, and add the introductionary paragraph. I'll ping you when that is merged into main.

**Comment by maelchiotti** [comment]
@IzzySoft done ☺️

**Comment by IzzySoft** [comment]
Thanks! Perfect for IzzyOnDroid. Just keep in mind that F-Droid.org will convert all newlines to `<br>` (at IzzyOnDroid, the update fetcher takes care to clean that up, "compressing" the HTML to a single line to prevent fdroidserver/client from doing that), so that will look quite funny there. If you want to, I can provide you a `full_description.pl` where you can edit your HTML as it is now and then run the Perl script to produce the proper "compressed" `full_description.txt`: [full_description.pl.txt](https://github.com/user-attachments/files/15838258/full_description.pl.txt) (had to add the `.txt` so Github allows me to attach it, so please remove that and replace the part following `__DATA__` with your full description. And yes, that description is from where this Perl script originates).

**Comment by maelchiotti** [comment]
I added the perl scripts as you said, and added a small batch script to run them all at once. Works beautifully!

```bash
#!/usr/bin/env bash

for d in */
do
  (
    cd "$d" || exit
    language=$(basename "$d")
    printf "\nGenerating full_description.txt for language %s\n" "$language"
    perl full_description.pl
  )
done
```

**Comment by IzzySoft** [comment]
Cool! Glad to read! :star_struck:

**Pull request closed without merging**
